{
    'name': 'Sentinela — Monitoramento de Sensores',
    'version': '18.0.1.0.0',
    'category': 'Manufacturing/Maintenance',
    'summary': 'Cadastro e monitoramento de sensores industriais (CME hospitalar e outros verticais)',
    'depends': ['base', 'mail'],
    'data': [
        'security/security_rules.xml',
        'security/ir.model.access.csv',
        'data/area_category_data.xml',
        'data/measurement_type_data.xml',
        'data/file_ledger_cron_data.xml',
        'views/site_views.xml',
        'views/dashboard_config_views.xml',
        'views/area_views.xml',
        'views/hub_views.xml',
        'views/coletor_views.xml',
        'views/sensor_views.xml',
        'views/alarm_threshold_views.xml',
        'views/alarm_event_views.xml',
        'views/file_ledger_views.xml',
        'views/rs485_modbus_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
